language: ruby
rvm:
  #- "1.9.2"
  - "1.9.3"
  - "2.0.0"
  #- jruby-19mode # JRuby in 1.9 mode
  #- rbx-19mode
before_script:
  - cd test/dummy
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake db:seed
  - cd ../..

script: bundle exec cucumber
