language: ruby
rvm:
  - "1.9.3"
  - "2.2.0"
  - "2.2.2"
  - ruby-head
matrix:
  allow_failures:
    - rvm: "1.9.3"
    - rvm: "2.2.0"
    - rvm: ruby-head
install: bundle install --jobs=3 --retry=3 --no-deployment
sudo: false
