language: ruby
gemfile:
  - gemfiles/rails_5_devise_4.gemfile
  - gemfiles/rails_4_devise_3.gemfile
  - gemfiles/ruby_1.9.3_rails_3.2.gemfile
rvm:
  - "1.9.3"
  - "2.2.2"
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5_devise_4.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4_devise_3.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/ruby_1.9.3_rails_3.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4_devise_3.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/ruby_1.9.3_rails_3.2.gemfile
install: bundle install --jobs=3 --retry=3 --no-deployment
sudo: false
